version: '3'

services:
  endtoendtests:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - ./api:/api
    command:
      - /bin/bash
      - /api/Api.EndToEndTest/run.sh
    depends_on: 
      - redis
      - db
    environment:
      - AppUrl=http://*:5000      
      - RedisConn=redis
      - SqlConn=Server=mariadb;Database=valuesDb;Uid=anuser;Pwd=apassword;SslMode=none;
    ports:
      - "5000:5000"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
 
  db:
    container_name: mariadb
    build:
      context: sql/
      dockerfile: Dockerfile
    restart: always


