version: '3'

services:

  api:
    build:
      context: api/
      dockerfile: Dockerfile
    depends_on: 
      - redis
      - db
    environment:
      - AppUrl=http://localhost:5000
      - RedisConn=localhost
      - SqlConn=Server=mariadb;Database=valuesDb;Uid=anuser;Pwd=apassword;SslMode=none;
    ports:
      - "5000:80"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
 
  db:
    container_name: mariadb
    build:
      context: sql/
      dockerfile: Dockerfile
    restart: always